import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { Student } from '@/types';
import { toast } from 'sonner';

export const useStudents = () => {
  return useQuery({
    queryKey: ['students'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('students')
        .select('*')
        .order('full_name');
      
      if (error) throw error;
      return data as Student[];
    },
  });
};

export const useAddStudent = () => {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async (student: Omit<Student, 'id' | 'student_unique_id' | 'created_at' | 'updated_at'>) => {
      const { data, error } = await supabase
        .from('students')
        .insert({
          nisn: student.nisn,
          full_name: student.full_name,
          class_name: student.class_name,
          major: student.major,
          is_active: student.is_active,
          student_unique_id: '', // Will be generated by trigger
        })
        .select()
        .single();
      
      if (error) throw error;
      return data as Student;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['students'] });
      toast.success('Siswa berhasil ditambahkan!');
    },
    onError: (error) => {
      toast.error('Gagal menambahkan siswa: ' + error.message);
    },
  });
};

export const useUpdateStudent = () => {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async ({ id, ...updates }: Partial<Student> & { id: string }) => {
      const { data, error } = await supabase
        .from('students')
        .update(updates)
        .eq('id', id)
        .select()
        .single();
      
      if (error) throw error;
      return data as Student;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['students'] });
      toast.success('Data siswa berhasil diperbarui!');
    },
    onError: (error) => {
      toast.error('Gagal memperbarui siswa: ' + error.message);
    },
  });
};

export const useDeleteStudent = () => {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from('students')
        .delete()
        .eq('id', id);
      
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['students'] });
      toast.success('Siswa berhasil dihapus!');
    },
    onError: (error) => {
      toast.error('Gagal menghapus siswa: ' + error.message);
    },
  });
};

export const useStudentByUniqueId = (uniqueId: string) => {
  return useQuery({
    queryKey: ['student', uniqueId],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('students')
        .select('*')
        .eq('student_unique_id', uniqueId)
        .maybeSingle();
      
      if (error) throw error;
      return data as Student | null;
    },
    enabled: !!uniqueId,
  });
};
